

AUGMENTATION_FLIPH = "flipH"
AUGMENTATION_FLIPV = "flipV"
AUGMENTATION_ROTATION = "rot"
AUGMENTATION_SCALE = "scale"
AUGMENTATION_RANDOM = "random"
AUGMENTATION_NONE = "none"




AUGMENTATION_CHOICES = [
                AUGMENTATION_NONE,
                AUGMENTATION_FLIPH,
                AUGMENTATION_FLIPV,
                AUGMENTATION_ROTATION,
                AUGMENTATION_SCALE,
                AUGMENTATION_RANDOM
                ]




kPIXEL_VALUE_FOR_MASKING = -1
kNUMBER_CHANNELS = 3


KEY_RESULT="result"
